/**
 * Client-side search for read-only / static deployments.
 *
 * Loads the prebuilt index (`public/api/search-index.json`, generated by
 * `scripts/prerender-api.ts`) once per session, then runs the same scoring
 * logic the server uses (`~/shared/search/scoring`) directly in the browser
 * — no `/api/search` round-trip.
 */

import {
  search,
  type SearchFilters,
  type SearchResult,
} from '~/shared/search/scoring';
import { apiUrl } from '~/utils/readOnly';

let indexPromise: Promise<SearchResult[]> | null = null;

export function loadIndex(): Promise<SearchResult[]> {
  if (!indexPromise) {
    indexPromise = fetch(apiUrl('/api/search-index'))
      .then((r) => {
        if (!r.ok)
          throw new Error(`Failed to load search index: HTTP ${r.status}`);
        return r.json() as Promise<SearchResult[]>;
      })
      .catch((err) => {
        // Reset so a retry can fetch again instead of being stuck on the rejection.
        indexPromise = null;
        throw err;
      });
  }
  return indexPromise;
}

export async function searchStatic(
  query: string,
  filters: SearchFilters,
  limit: number = 50,
): Promise<{ results: SearchResult[]; timing: number }> {
  const start = Date.now();
  const index = await loadIndex();
  const results = search(index, query, filters, limit);
  return { results, timing: Date.now() - start };
}
