# OpenPrintTag Schema Configuration
SCHEMA_REPO_URL="https://github.com/OpenPrintTag/openprinttag-architecture.git"
SCHEMA_COMMIT="693ff6c1d8cfa7ed5a781d9f855eb21715f8f301"
SCHEMA_SPARSE_PATH="schema/generated/opt_db_schema"
SCHEMA_TARGET_DIR="./openprinttag"
