/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnumRouteImport } from './routes/enum'
import { Route as ContainersRouteImport } from './routes/containers'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnumIndexRouteImport } from './routes/enum.index'
import { Route as ContainersIndexRouteImport } from './routes/containers/index'
import { Route as BrandsIndexRouteImport } from './routes/brands/index'
import { Route as EnumTableRouteImport } from './routes/enum.$table'
import { Route as ContainersCreateRouteImport } from './routes/containers/create'
import { Route as ContainersContainerIdRouteImport } from './routes/containers/$containerId'
import { Route as BrandsBrandIdRouteImport } from './routes/brands/$brandId'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiSchemaRouteImport } from './routes/api/schema'
import { Route as ApiPackagesRouteImport } from './routes/api/packages'
import { Route as ApiMaterialsRouteImport } from './routes/api/materials'
import { Route as ApiEnumRouteImport } from './routes/api/enum'
import { Route as ApiContainersRouteImport } from './routes/api/containers'
import { Route as ApiBrandsRouteImport } from './routes/api/brands'
import { Route as ContainersContainerIdIndexRouteImport } from './routes/containers/$containerId/index'
import { Route as BrandsBrandIdIndexRouteImport } from './routes/brands/$brandId/index'
import { Route as ContainersContainerIdEditRouteImport } from './routes/containers/$containerId/edit'
import { Route as BrandsBrandIdPackagesRouteImport } from './routes/brands/$brandId/packages'
import { Route as BrandsBrandIdMaterialsRouteImport } from './routes/brands/$brandId/materials'
import { Route as BrandsBrandIdContainersRouteImport } from './routes/brands/$brandId/containers'
import { Route as ApiSchemaEntityRouteImport } from './routes/api/schema.$entity'
import { Route as ApiMaterialsMaterialIdRouteImport } from './routes/api/materials.$materialId'
import { Route as ApiEnumTableRouteImport } from './routes/api/enum.$table'
import { Route as ApiContainersNewRouteImport } from './routes/api/containers.new'
import { Route as ApiContainersContainerIdRouteImport } from './routes/api/containers.$containerId'
import { Route as ApiBrandsBasicRouteImport } from './routes/api/brands.basic'
import { Route as ApiBrandsBrandIdRouteImport } from './routes/api/brands.$brandId'
import { Route as BrandsBrandIdPackagesCreateRouteImport } from './routes/brands/$brandId/packages/create'
import { Route as BrandsBrandIdPackagesPackageIdRouteImport } from './routes/brands/$brandId/packages/$packageId'
import { Route as BrandsBrandIdMaterialsCreateRouteImport } from './routes/brands/$brandId/materials/create'
import { Route as BrandsBrandIdMaterialsMaterialIdRouteImport } from './routes/brands/$brandId/materials/$materialId'
import { Route as BrandsBrandIdContainersCreateRouteImport } from './routes/brands/$brandId/containers/create'
import { Route as BrandsBrandIdContainersContainerIdRouteImport } from './routes/brands/$brandId/containers/$containerId'
import { Route as ApiBrandsBrandIdPackagesRouteImport } from './routes/api/brands.$brandId.packages'
import { Route as ApiBrandsBrandIdMaterialsRouteImport } from './routes/api/brands.$brandId.materials'
import { Route as ApiBrandsBrandIdCountsRouteImport } from './routes/api/brands.$brandId.counts'
import { Route as BrandsBrandIdPackagesPackageIdIndexRouteImport } from './routes/brands/$brandId/packages/$packageId/index'
import { Route as BrandsBrandIdMaterialsMaterialIdIndexRouteImport } from './routes/brands/$brandId/materials/$materialId/index'
import { Route as BrandsBrandIdContainersContainerIdIndexRouteImport } from './routes/brands/$brandId/containers/$containerId/index'
import { Route as BrandsBrandIdPackagesPackageIdEditRouteImport } from './routes/brands/$brandId/packages/$packageId/edit'
import { Route as BrandsBrandIdMaterialsMaterialIdEditRouteImport } from './routes/brands/$brandId/materials/$materialId/edit'
import { Route as BrandsBrandIdContainersContainerIdEditRouteImport } from './routes/brands/$brandId/containers/$containerId/edit'
import { Route as ApiBrandsBrandIdPackagesNewRouteImport } from './routes/api/brands.$brandId.packages.new'
import { Route as ApiBrandsBrandIdPackagesPackageIdRouteImport } from './routes/api/brands.$brandId.packages.$packageId'
import { Route as ApiBrandsBrandIdMaterialsNewRouteImport } from './routes/api/brands.$brandId.materials.new'
import { Route as ApiBrandsBrandIdMaterialsMaterialIdRouteImport } from './routes/api/brands.$brandId.materials.$materialId'
import { Route as ApiAssetsBrandSlugMaterialSlugFilenameRouteImport } from './routes/api/assets.$brandSlug.$materialSlug.$filename'

const EnumRoute = EnumRouteImport.update({
  id: '/enum',
  path: '/enum',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersRoute = ContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnumIndexRoute = EnumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnumRoute,
} as any)
const ContainersIndexRoute = ContainersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContainersRoute,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsRoute,
} as any)
const EnumTableRoute = EnumTableRouteImport.update({
  id: '/$table',
  path: '/$table',
  getParentRoute: () => EnumRoute,
} as any)
const ContainersCreateRoute = ContainersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ContainersRoute,
} as any)
const ContainersContainerIdRoute = ContainersContainerIdRouteImport.update({
  id: '/$containerId',
  path: '/$containerId',
  getParentRoute: () => ContainersRoute,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/$brandId',
  path: '/$brandId',
  getParentRoute: () => BrandsRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchemaRoute = ApiSchemaRouteImport.update({
  id: '/api/schema',
  path: '/api/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPackagesRoute = ApiPackagesRouteImport.update({
  id: '/api/packages',
  path: '/api/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaterialsRoute = ApiMaterialsRouteImport.update({
  id: '/api/materials',
  path: '/api/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnumRoute = ApiEnumRouteImport.update({
  id: '/api/enum',
  path: '/api/enum',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContainersRoute = ApiContainersRouteImport.update({
  id: '/api/containers',
  path: '/api/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandsRoute = ApiBrandsRouteImport.update({
  id: '/api/brands',
  path: '/api/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersContainerIdIndexRoute =
  ContainersContainerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ContainersContainerIdRoute,
  } as any)
const BrandsBrandIdIndexRoute = BrandsBrandIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsBrandIdRoute,
} as any)
const ContainersContainerIdEditRoute =
  ContainersContainerIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ContainersContainerIdRoute,
  } as any)
const BrandsBrandIdPackagesRoute = BrandsBrandIdPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => BrandsBrandIdRoute,
} as any)
const BrandsBrandIdMaterialsRoute = BrandsBrandIdMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => BrandsBrandIdRoute,
} as any)
const BrandsBrandIdContainersRoute = BrandsBrandIdContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => BrandsBrandIdRoute,
} as any)
const ApiSchemaEntityRoute = ApiSchemaEntityRouteImport.update({
  id: '/$entity',
  path: '/$entity',
  getParentRoute: () => ApiSchemaRoute,
} as any)
const ApiMaterialsMaterialIdRoute = ApiMaterialsMaterialIdRouteImport.update({
  id: '/$materialId',
  path: '/$materialId',
  getParentRoute: () => ApiMaterialsRoute,
} as any)
const ApiEnumTableRoute = ApiEnumTableRouteImport.update({
  id: '/$table',
  path: '/$table',
  getParentRoute: () => ApiEnumRoute,
} as any)
const ApiContainersNewRoute = ApiContainersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ApiContainersRoute,
} as any)
const ApiContainersContainerIdRoute =
  ApiContainersContainerIdRouteImport.update({
    id: '/$containerId',
    path: '/$containerId',
    getParentRoute: () => ApiContainersRoute,
  } as any)
const ApiBrandsBasicRoute = ApiBrandsBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => ApiBrandsRoute,
} as any)
const ApiBrandsBrandIdRoute = ApiBrandsBrandIdRouteImport.update({
  id: '/$brandId',
  path: '/$brandId',
  getParentRoute: () => ApiBrandsRoute,
} as any)
const BrandsBrandIdPackagesCreateRoute =
  BrandsBrandIdPackagesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => BrandsBrandIdPackagesRoute,
  } as any)
const BrandsBrandIdPackagesPackageIdRoute =
  BrandsBrandIdPackagesPackageIdRouteImport.update({
    id: '/$packageId',
    path: '/$packageId',
    getParentRoute: () => BrandsBrandIdPackagesRoute,
  } as any)
const BrandsBrandIdMaterialsCreateRoute =
  BrandsBrandIdMaterialsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => BrandsBrandIdMaterialsRoute,
  } as any)
const BrandsBrandIdMaterialsMaterialIdRoute =
  BrandsBrandIdMaterialsMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => BrandsBrandIdMaterialsRoute,
  } as any)
const BrandsBrandIdContainersCreateRoute =
  BrandsBrandIdContainersCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => BrandsBrandIdContainersRoute,
  } as any)
const BrandsBrandIdContainersContainerIdRoute =
  BrandsBrandIdContainersContainerIdRouteImport.update({
    id: '/$containerId',
    path: '/$containerId',
    getParentRoute: () => BrandsBrandIdContainersRoute,
  } as any)
const ApiBrandsBrandIdPackagesRoute =
  ApiBrandsBrandIdPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => ApiBrandsBrandIdRoute,
  } as any)
const ApiBrandsBrandIdMaterialsRoute =
  ApiBrandsBrandIdMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => ApiBrandsBrandIdRoute,
  } as any)
const ApiBrandsBrandIdCountsRoute = ApiBrandsBrandIdCountsRouteImport.update({
  id: '/counts',
  path: '/counts',
  getParentRoute: () => ApiBrandsBrandIdRoute,
} as any)
const BrandsBrandIdPackagesPackageIdIndexRoute =
  BrandsBrandIdPackagesPackageIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BrandsBrandIdPackagesPackageIdRoute,
  } as any)
const BrandsBrandIdMaterialsMaterialIdIndexRoute =
  BrandsBrandIdMaterialsMaterialIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BrandsBrandIdMaterialsMaterialIdRoute,
  } as any)
const BrandsBrandIdContainersContainerIdIndexRoute =
  BrandsBrandIdContainersContainerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BrandsBrandIdContainersContainerIdRoute,
  } as any)
const BrandsBrandIdPackagesPackageIdEditRoute =
  BrandsBrandIdPackagesPackageIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => BrandsBrandIdPackagesPackageIdRoute,
  } as any)
const BrandsBrandIdMaterialsMaterialIdEditRoute =
  BrandsBrandIdMaterialsMaterialIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => BrandsBrandIdMaterialsMaterialIdRoute,
  } as any)
const BrandsBrandIdContainersContainerIdEditRoute =
  BrandsBrandIdContainersContainerIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => BrandsBrandIdContainersContainerIdRoute,
  } as any)
const ApiBrandsBrandIdPackagesNewRoute =
  ApiBrandsBrandIdPackagesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ApiBrandsBrandIdPackagesRoute,
  } as any)
const ApiBrandsBrandIdPackagesPackageIdRoute =
  ApiBrandsBrandIdPackagesPackageIdRouteImport.update({
    id: '/$packageId',
    path: '/$packageId',
    getParentRoute: () => ApiBrandsBrandIdPackagesRoute,
  } as any)
const ApiBrandsBrandIdMaterialsNewRoute =
  ApiBrandsBrandIdMaterialsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ApiBrandsBrandIdMaterialsRoute,
  } as any)
const ApiBrandsBrandIdMaterialsMaterialIdRoute =
  ApiBrandsBrandIdMaterialsMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => ApiBrandsBrandIdMaterialsRoute,
  } as any)
const ApiAssetsBrandSlugMaterialSlugFilenameRoute =
  ApiAssetsBrandSlugMaterialSlugFilenameRouteImport.update({
    id: '/api/assets/$brandSlug/$materialSlug/$filename',
    path: '/api/assets/$brandSlug/$materialSlug/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRouteWithChildren
  '/containers': typeof ContainersRouteWithChildren
  '/enum': typeof EnumRouteWithChildren
  '/api/brands': typeof ApiBrandsRouteWithChildren
  '/api/containers': typeof ApiContainersRouteWithChildren
  '/api/enum': typeof ApiEnumRouteWithChildren
  '/api/materials': typeof ApiMaterialsRouteWithChildren
  '/api/packages': typeof ApiPackagesRoute
  '/api/schema': typeof ApiSchemaRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/brands/$brandId': typeof BrandsBrandIdRouteWithChildren
  '/containers/$containerId': typeof ContainersContainerIdRouteWithChildren
  '/containers/create': typeof ContainersCreateRoute
  '/enum/$table': typeof EnumTableRoute
  '/brands/': typeof BrandsIndexRoute
  '/containers/': typeof ContainersIndexRoute
  '/enum/': typeof EnumIndexRoute
  '/api/brands/$brandId': typeof ApiBrandsBrandIdRouteWithChildren
  '/api/brands/basic': typeof ApiBrandsBasicRoute
  '/api/containers/$containerId': typeof ApiContainersContainerIdRoute
  '/api/containers/new': typeof ApiContainersNewRoute
  '/api/enum/$table': typeof ApiEnumTableRoute
  '/api/materials/$materialId': typeof ApiMaterialsMaterialIdRoute
  '/api/schema/$entity': typeof ApiSchemaEntityRoute
  '/brands/$brandId/containers': typeof BrandsBrandIdContainersRouteWithChildren
  '/brands/$brandId/materials': typeof BrandsBrandIdMaterialsRouteWithChildren
  '/brands/$brandId/packages': typeof BrandsBrandIdPackagesRouteWithChildren
  '/containers/$containerId/edit': typeof ContainersContainerIdEditRoute
  '/brands/$brandId/': typeof BrandsBrandIdIndexRoute
  '/containers/$containerId/': typeof ContainersContainerIdIndexRoute
  '/api/brands/$brandId/counts': typeof ApiBrandsBrandIdCountsRoute
  '/api/brands/$brandId/materials': typeof ApiBrandsBrandIdMaterialsRouteWithChildren
  '/api/brands/$brandId/packages': typeof ApiBrandsBrandIdPackagesRouteWithChildren
  '/brands/$brandId/containers/$containerId': typeof BrandsBrandIdContainersContainerIdRouteWithChildren
  '/brands/$brandId/containers/create': typeof BrandsBrandIdContainersCreateRoute
  '/brands/$brandId/materials/$materialId': typeof BrandsBrandIdMaterialsMaterialIdRouteWithChildren
  '/brands/$brandId/materials/create': typeof BrandsBrandIdMaterialsCreateRoute
  '/brands/$brandId/packages/$packageId': typeof BrandsBrandIdPackagesPackageIdRouteWithChildren
  '/brands/$brandId/packages/create': typeof BrandsBrandIdPackagesCreateRoute
  '/api/assets/$brandSlug/$materialSlug/$filename': typeof ApiAssetsBrandSlugMaterialSlugFilenameRoute
  '/api/brands/$brandId/materials/$materialId': typeof ApiBrandsBrandIdMaterialsMaterialIdRoute
  '/api/brands/$brandId/materials/new': typeof ApiBrandsBrandIdMaterialsNewRoute
  '/api/brands/$brandId/packages/$packageId': typeof ApiBrandsBrandIdPackagesPackageIdRoute
  '/api/brands/$brandId/packages/new': typeof ApiBrandsBrandIdPackagesNewRoute
  '/brands/$brandId/containers/$containerId/edit': typeof BrandsBrandIdContainersContainerIdEditRoute
  '/brands/$brandId/materials/$materialId/edit': typeof BrandsBrandIdMaterialsMaterialIdEditRoute
  '/brands/$brandId/packages/$packageId/edit': typeof BrandsBrandIdPackagesPackageIdEditRoute
  '/brands/$brandId/containers/$containerId/': typeof BrandsBrandIdContainersContainerIdIndexRoute
  '/brands/$brandId/materials/$materialId/': typeof BrandsBrandIdMaterialsMaterialIdIndexRoute
  '/brands/$brandId/packages/$packageId/': typeof BrandsBrandIdPackagesPackageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/brands': typeof ApiBrandsRouteWithChildren
  '/api/containers': typeof ApiContainersRouteWithChildren
  '/api/enum': typeof ApiEnumRouteWithChildren
  '/api/materials': typeof ApiMaterialsRouteWithChildren
  '/api/packages': typeof ApiPackagesRoute
  '/api/schema': typeof ApiSchemaRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/containers/create': typeof ContainersCreateRoute
  '/enum/$table': typeof EnumTableRoute
  '/brands': typeof BrandsIndexRoute
  '/containers': typeof ContainersIndexRoute
  '/enum': typeof EnumIndexRoute
  '/api/brands/$brandId': typeof ApiBrandsBrandIdRouteWithChildren
  '/api/brands/basic': typeof ApiBrandsBasicRoute
  '/api/containers/$containerId': typeof ApiContainersContainerIdRoute
  '/api/containers/new': typeof ApiContainersNewRoute
  '/api/enum/$table': typeof ApiEnumTableRoute
  '/api/materials/$materialId': typeof ApiMaterialsMaterialIdRoute
  '/api/schema/$entity': typeof ApiSchemaEntityRoute
  '/brands/$brandId/containers': typeof BrandsBrandIdContainersRouteWithChildren
  '/brands/$brandId/materials': typeof BrandsBrandIdMaterialsRouteWithChildren
  '/brands/$brandId/packages': typeof BrandsBrandIdPackagesRouteWithChildren
  '/containers/$containerId/edit': typeof ContainersContainerIdEditRoute
  '/brands/$brandId': typeof BrandsBrandIdIndexRoute
  '/containers/$containerId': typeof ContainersContainerIdIndexRoute
  '/api/brands/$brandId/counts': typeof ApiBrandsBrandIdCountsRoute
  '/api/brands/$brandId/materials': typeof ApiBrandsBrandIdMaterialsRouteWithChildren
  '/api/brands/$brandId/packages': typeof ApiBrandsBrandIdPackagesRouteWithChildren
  '/brands/$brandId/containers/create': typeof BrandsBrandIdContainersCreateRoute
  '/brands/$brandId/materials/create': typeof BrandsBrandIdMaterialsCreateRoute
  '/brands/$brandId/packages/create': typeof BrandsBrandIdPackagesCreateRoute
  '/api/assets/$brandSlug/$materialSlug/$filename': typeof ApiAssetsBrandSlugMaterialSlugFilenameRoute
  '/api/brands/$brandId/materials/$materialId': typeof ApiBrandsBrandIdMaterialsMaterialIdRoute
  '/api/brands/$brandId/materials/new': typeof ApiBrandsBrandIdMaterialsNewRoute
  '/api/brands/$brandId/packages/$packageId': typeof ApiBrandsBrandIdPackagesPackageIdRoute
  '/api/brands/$brandId/packages/new': typeof ApiBrandsBrandIdPackagesNewRoute
  '/brands/$brandId/containers/$containerId/edit': typeof BrandsBrandIdContainersContainerIdEditRoute
  '/brands/$brandId/materials/$materialId/edit': typeof BrandsBrandIdMaterialsMaterialIdEditRoute
  '/brands/$brandId/packages/$packageId/edit': typeof BrandsBrandIdPackagesPackageIdEditRoute
  '/brands/$brandId/containers/$containerId': typeof BrandsBrandIdContainersContainerIdIndexRoute
  '/brands/$brandId/materials/$materialId': typeof BrandsBrandIdMaterialsMaterialIdIndexRoute
  '/brands/$brandId/packages/$packageId': typeof BrandsBrandIdPackagesPackageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRouteWithChildren
  '/containers': typeof ContainersRouteWithChildren
  '/enum': typeof EnumRouteWithChildren
  '/api/brands': typeof ApiBrandsRouteWithChildren
  '/api/containers': typeof ApiContainersRouteWithChildren
  '/api/enum': typeof ApiEnumRouteWithChildren
  '/api/materials': typeof ApiMaterialsRouteWithChildren
  '/api/packages': typeof ApiPackagesRoute
  '/api/schema': typeof ApiSchemaRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/upload': typeof ApiUploadRoute
  '/brands/$brandId': typeof BrandsBrandIdRouteWithChildren
  '/containers/$containerId': typeof ContainersContainerIdRouteWithChildren
  '/containers/create': typeof ContainersCreateRoute
  '/enum/$table': typeof EnumTableRoute
  '/brands/': typeof BrandsIndexRoute
  '/containers/': typeof ContainersIndexRoute
  '/enum/': typeof EnumIndexRoute
  '/api/brands/$brandId': typeof ApiBrandsBrandIdRouteWithChildren
  '/api/brands/basic': typeof ApiBrandsBasicRoute
  '/api/containers/$containerId': typeof ApiContainersContainerIdRoute
  '/api/containers/new': typeof ApiContainersNewRoute
  '/api/enum/$table': typeof ApiEnumTableRoute
  '/api/materials/$materialId': typeof ApiMaterialsMaterialIdRoute
  '/api/schema/$entity': typeof ApiSchemaEntityRoute
  '/brands/$brandId/containers': typeof BrandsBrandIdContainersRouteWithChildren
  '/brands/$brandId/materials': typeof BrandsBrandIdMaterialsRouteWithChildren
  '/brands/$brandId/packages': typeof BrandsBrandIdPackagesRouteWithChildren
  '/containers/$containerId/edit': typeof ContainersContainerIdEditRoute
  '/brands/$brandId/': typeof BrandsBrandIdIndexRoute
  '/containers/$containerId/': typeof ContainersContainerIdIndexRoute
  '/api/brands/$brandId/counts': typeof ApiBrandsBrandIdCountsRoute
  '/api/brands/$brandId/materials': typeof ApiBrandsBrandIdMaterialsRouteWithChildren
  '/api/brands/$brandId/packages': typeof ApiBrandsBrandIdPackagesRouteWithChildren
  '/brands/$brandId/containers/$containerId': typeof BrandsBrandIdContainersContainerIdRouteWithChildren
  '/brands/$brandId/containers/create': typeof BrandsBrandIdContainersCreateRoute
  '/brands/$brandId/materials/$materialId': typeof BrandsBrandIdMaterialsMaterialIdRouteWithChildren
  '/brands/$brandId/materials/create': typeof BrandsBrandIdMaterialsCreateRoute
  '/brands/$brandId/packages/$packageId': typeof BrandsBrandIdPackagesPackageIdRouteWithChildren
  '/brands/$brandId/packages/create': typeof BrandsBrandIdPackagesCreateRoute
  '/api/assets/$brandSlug/$materialSlug/$filename': typeof ApiAssetsBrandSlugMaterialSlugFilenameRoute
  '/api/brands/$brandId/materials/$materialId': typeof ApiBrandsBrandIdMaterialsMaterialIdRoute
  '/api/brands/$brandId/materials/new': typeof ApiBrandsBrandIdMaterialsNewRoute
  '/api/brands/$brandId/packages/$packageId': typeof ApiBrandsBrandIdPackagesPackageIdRoute
  '/api/brands/$brandId/packages/new': typeof ApiBrandsBrandIdPackagesNewRoute
  '/brands/$brandId/containers/$containerId/edit': typeof BrandsBrandIdContainersContainerIdEditRoute
  '/brands/$brandId/materials/$materialId/edit': typeof BrandsBrandIdMaterialsMaterialIdEditRoute
  '/brands/$brandId/packages/$packageId/edit': typeof BrandsBrandIdPackagesPackageIdEditRoute
  '/brands/$brandId/containers/$containerId/': typeof BrandsBrandIdContainersContainerIdIndexRoute
  '/brands/$brandId/materials/$materialId/': typeof BrandsBrandIdMaterialsMaterialIdIndexRoute
  '/brands/$brandId/packages/$packageId/': typeof BrandsBrandIdPackagesPackageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/containers'
    | '/enum'
    | '/api/brands'
    | '/api/containers'
    | '/api/enum'
    | '/api/materials'
    | '/api/packages'
    | '/api/schema'
    | '/api/search'
    | '/api/upload'
    | '/brands/$brandId'
    | '/containers/$containerId'
    | '/containers/create'
    | '/enum/$table'
    | '/brands/'
    | '/containers/'
    | '/enum/'
    | '/api/brands/$brandId'
    | '/api/brands/basic'
    | '/api/containers/$containerId'
    | '/api/containers/new'
    | '/api/enum/$table'
    | '/api/materials/$materialId'
    | '/api/schema/$entity'
    | '/brands/$brandId/containers'
    | '/brands/$brandId/materials'
    | '/brands/$brandId/packages'
    | '/containers/$containerId/edit'
    | '/brands/$brandId/'
    | '/containers/$containerId/'
    | '/api/brands/$brandId/counts'
    | '/api/brands/$brandId/materials'
    | '/api/brands/$brandId/packages'
    | '/brands/$brandId/containers/$containerId'
    | '/brands/$brandId/containers/create'
    | '/brands/$brandId/materials/$materialId'
    | '/brands/$brandId/materials/create'
    | '/brands/$brandId/packages/$packageId'
    | '/brands/$brandId/packages/create'
    | '/api/assets/$brandSlug/$materialSlug/$filename'
    | '/api/brands/$brandId/materials/$materialId'
    | '/api/brands/$brandId/materials/new'
    | '/api/brands/$brandId/packages/$packageId'
    | '/api/brands/$brandId/packages/new'
    | '/brands/$brandId/containers/$containerId/edit'
    | '/brands/$brandId/materials/$materialId/edit'
    | '/brands/$brandId/packages/$packageId/edit'
    | '/brands/$brandId/containers/$containerId/'
    | '/brands/$brandId/materials/$materialId/'
    | '/brands/$brandId/packages/$packageId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/brands'
    | '/api/containers'
    | '/api/enum'
    | '/api/materials'
    | '/api/packages'
    | '/api/schema'
    | '/api/search'
    | '/api/upload'
    | '/containers/create'
    | '/enum/$table'
    | '/brands'
    | '/containers'
    | '/enum'
    | '/api/brands/$brandId'
    | '/api/brands/basic'
    | '/api/containers/$containerId'
    | '/api/containers/new'
    | '/api/enum/$table'
    | '/api/materials/$materialId'
    | '/api/schema/$entity'
    | '/brands/$brandId/containers'
    | '/brands/$brandId/materials'
    | '/brands/$brandId/packages'
    | '/containers/$containerId/edit'
    | '/brands/$brandId'
    | '/containers/$containerId'
    | '/api/brands/$brandId/counts'
    | '/api/brands/$brandId/materials'
    | '/api/brands/$brandId/packages'
    | '/brands/$brandId/containers/create'
    | '/brands/$brandId/materials/create'
    | '/brands/$brandId/packages/create'
    | '/api/assets/$brandSlug/$materialSlug/$filename'
    | '/api/brands/$brandId/materials/$materialId'
    | '/api/brands/$brandId/materials/new'
    | '/api/brands/$brandId/packages/$packageId'
    | '/api/brands/$brandId/packages/new'
    | '/brands/$brandId/containers/$containerId/edit'
    | '/brands/$brandId/materials/$materialId/edit'
    | '/brands/$brandId/packages/$packageId/edit'
    | '/brands/$brandId/containers/$containerId'
    | '/brands/$brandId/materials/$materialId'
    | '/brands/$brandId/packages/$packageId'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/containers'
    | '/enum'
    | '/api/brands'
    | '/api/containers'
    | '/api/enum'
    | '/api/materials'
    | '/api/packages'
    | '/api/schema'
    | '/api/search'
    | '/api/upload'
    | '/brands/$brandId'
    | '/containers/$containerId'
    | '/containers/create'
    | '/enum/$table'
    | '/brands/'
    | '/containers/'
    | '/enum/'
    | '/api/brands/$brandId'
    | '/api/brands/basic'
    | '/api/containers/$containerId'
    | '/api/containers/new'
    | '/api/enum/$table'
    | '/api/materials/$materialId'
    | '/api/schema/$entity'
    | '/brands/$brandId/containers'
    | '/brands/$brandId/materials'
    | '/brands/$brandId/packages'
    | '/containers/$containerId/edit'
    | '/brands/$brandId/'
    | '/containers/$containerId/'
    | '/api/brands/$brandId/counts'
    | '/api/brands/$brandId/materials'
    | '/api/brands/$brandId/packages'
    | '/brands/$brandId/containers/$containerId'
    | '/brands/$brandId/containers/create'
    | '/brands/$brandId/materials/$materialId'
    | '/brands/$brandId/materials/create'
    | '/brands/$brandId/packages/$packageId'
    | '/brands/$brandId/packages/create'
    | '/api/assets/$brandSlug/$materialSlug/$filename'
    | '/api/brands/$brandId/materials/$materialId'
    | '/api/brands/$brandId/materials/new'
    | '/api/brands/$brandId/packages/$packageId'
    | '/api/brands/$brandId/packages/new'
    | '/brands/$brandId/containers/$containerId/edit'
    | '/brands/$brandId/materials/$materialId/edit'
    | '/brands/$brandId/packages/$packageId/edit'
    | '/brands/$brandId/containers/$containerId/'
    | '/brands/$brandId/materials/$materialId/'
    | '/brands/$brandId/packages/$packageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRoute: typeof BrandsRouteWithChildren
  ContainersRoute: typeof ContainersRouteWithChildren
  EnumRoute: typeof EnumRouteWithChildren
  ApiBrandsRoute: typeof ApiBrandsRouteWithChildren
  ApiContainersRoute: typeof ApiContainersRouteWithChildren
  ApiEnumRoute: typeof ApiEnumRouteWithChildren
  ApiMaterialsRoute: typeof ApiMaterialsRouteWithChildren
  ApiPackagesRoute: typeof ApiPackagesRoute
  ApiSchemaRoute: typeof ApiSchemaRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAssetsBrandSlugMaterialSlugFilenameRoute: typeof ApiAssetsBrandSlugMaterialSlugFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/enum': {
      id: '/enum'
      path: '/enum'
      fullPath: '/enum'
      preLoaderRoute: typeof EnumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers': {
      id: '/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof ContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enum/': {
      id: '/enum/'
      path: '/'
      fullPath: '/enum/'
      preLoaderRoute: typeof EnumIndexRouteImport
      parentRoute: typeof EnumRoute
    }
    '/containers/': {
      id: '/containers/'
      path: '/'
      fullPath: '/containers/'
      preLoaderRoute: typeof ContainersIndexRouteImport
      parentRoute: typeof ContainersRoute
    }
    '/brands/': {
      id: '/brands/'
      path: '/'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/enum/$table': {
      id: '/enum/$table'
      path: '/$table'
      fullPath: '/enum/$table'
      preLoaderRoute: typeof EnumTableRouteImport
      parentRoute: typeof EnumRoute
    }
    '/containers/create': {
      id: '/containers/create'
      path: '/create'
      fullPath: '/containers/create'
      preLoaderRoute: typeof ContainersCreateRouteImport
      parentRoute: typeof ContainersRoute
    }
    '/containers/$containerId': {
      id: '/containers/$containerId'
      path: '/$containerId'
      fullPath: '/containers/$containerId'
      preLoaderRoute: typeof ContainersContainerIdRouteImport
      parentRoute: typeof ContainersRoute
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schema': {
      id: '/api/schema'
      path: '/api/schema'
      fullPath: '/api/schema'
      preLoaderRoute: typeof ApiSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/packages': {
      id: '/api/packages'
      path: '/api/packages'
      fullPath: '/api/packages'
      preLoaderRoute: typeof ApiPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/materials': {
      id: '/api/materials'
      path: '/api/materials'
      fullPath: '/api/materials'
      preLoaderRoute: typeof ApiMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enum': {
      id: '/api/enum'
      path: '/api/enum'
      fullPath: '/api/enum'
      preLoaderRoute: typeof ApiEnumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/containers': {
      id: '/api/containers'
      path: '/api/containers'
      fullPath: '/api/containers'
      preLoaderRoute: typeof ApiContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brands': {
      id: '/api/brands'
      path: '/api/brands'
      fullPath: '/api/brands'
      preLoaderRoute: typeof ApiBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$containerId/': {
      id: '/containers/$containerId/'
      path: '/'
      fullPath: '/containers/$containerId/'
      preLoaderRoute: typeof ContainersContainerIdIndexRouteImport
      parentRoute: typeof ContainersContainerIdRoute
    }
    '/brands/$brandId/': {
      id: '/brands/$brandId/'
      path: '/'
      fullPath: '/brands/$brandId/'
      preLoaderRoute: typeof BrandsBrandIdIndexRouteImport
      parentRoute: typeof BrandsBrandIdRoute
    }
    '/containers/$containerId/edit': {
      id: '/containers/$containerId/edit'
      path: '/edit'
      fullPath: '/containers/$containerId/edit'
      preLoaderRoute: typeof ContainersContainerIdEditRouteImport
      parentRoute: typeof ContainersContainerIdRoute
    }
    '/brands/$brandId/packages': {
      id: '/brands/$brandId/packages'
      path: '/packages'
      fullPath: '/brands/$brandId/packages'
      preLoaderRoute: typeof BrandsBrandIdPackagesRouteImport
      parentRoute: typeof BrandsBrandIdRoute
    }
    '/brands/$brandId/materials': {
      id: '/brands/$brandId/materials'
      path: '/materials'
      fullPath: '/brands/$brandId/materials'
      preLoaderRoute: typeof BrandsBrandIdMaterialsRouteImport
      parentRoute: typeof BrandsBrandIdRoute
    }
    '/brands/$brandId/containers': {
      id: '/brands/$brandId/containers'
      path: '/containers'
      fullPath: '/brands/$brandId/containers'
      preLoaderRoute: typeof BrandsBrandIdContainersRouteImport
      parentRoute: typeof BrandsBrandIdRoute
    }
    '/api/schema/$entity': {
      id: '/api/schema/$entity'
      path: '/$entity'
      fullPath: '/api/schema/$entity'
      preLoaderRoute: typeof ApiSchemaEntityRouteImport
      parentRoute: typeof ApiSchemaRoute
    }
    '/api/materials/$materialId': {
      id: '/api/materials/$materialId'
      path: '/$materialId'
      fullPath: '/api/materials/$materialId'
      preLoaderRoute: typeof ApiMaterialsMaterialIdRouteImport
      parentRoute: typeof ApiMaterialsRoute
    }
    '/api/enum/$table': {
      id: '/api/enum/$table'
      path: '/$table'
      fullPath: '/api/enum/$table'
      preLoaderRoute: typeof ApiEnumTableRouteImport
      parentRoute: typeof ApiEnumRoute
    }
    '/api/containers/new': {
      id: '/api/containers/new'
      path: '/new'
      fullPath: '/api/containers/new'
      preLoaderRoute: typeof ApiContainersNewRouteImport
      parentRoute: typeof ApiContainersRoute
    }
    '/api/containers/$containerId': {
      id: '/api/containers/$containerId'
      path: '/$containerId'
      fullPath: '/api/containers/$containerId'
      preLoaderRoute: typeof ApiContainersContainerIdRouteImport
      parentRoute: typeof ApiContainersRoute
    }
    '/api/brands/basic': {
      id: '/api/brands/basic'
      path: '/basic'
      fullPath: '/api/brands/basic'
      preLoaderRoute: typeof ApiBrandsBasicRouteImport
      parentRoute: typeof ApiBrandsRoute
    }
    '/api/brands/$brandId': {
      id: '/api/brands/$brandId'
      path: '/$brandId'
      fullPath: '/api/brands/$brandId'
      preLoaderRoute: typeof ApiBrandsBrandIdRouteImport
      parentRoute: typeof ApiBrandsRoute
    }
    '/brands/$brandId/packages/create': {
      id: '/brands/$brandId/packages/create'
      path: '/create'
      fullPath: '/brands/$brandId/packages/create'
      preLoaderRoute: typeof BrandsBrandIdPackagesCreateRouteImport
      parentRoute: typeof BrandsBrandIdPackagesRoute
    }
    '/brands/$brandId/packages/$packageId': {
      id: '/brands/$brandId/packages/$packageId'
      path: '/$packageId'
      fullPath: '/brands/$brandId/packages/$packageId'
      preLoaderRoute: typeof BrandsBrandIdPackagesPackageIdRouteImport
      parentRoute: typeof BrandsBrandIdPackagesRoute
    }
    '/brands/$brandId/materials/create': {
      id: '/brands/$brandId/materials/create'
      path: '/create'
      fullPath: '/brands/$brandId/materials/create'
      preLoaderRoute: typeof BrandsBrandIdMaterialsCreateRouteImport
      parentRoute: typeof BrandsBrandIdMaterialsRoute
    }
    '/brands/$brandId/materials/$materialId': {
      id: '/brands/$brandId/materials/$materialId'
      path: '/$materialId'
      fullPath: '/brands/$brandId/materials/$materialId'
      preLoaderRoute: typeof BrandsBrandIdMaterialsMaterialIdRouteImport
      parentRoute: typeof BrandsBrandIdMaterialsRoute
    }
    '/brands/$brandId/containers/create': {
      id: '/brands/$brandId/containers/create'
      path: '/create'
      fullPath: '/brands/$brandId/containers/create'
      preLoaderRoute: typeof BrandsBrandIdContainersCreateRouteImport
      parentRoute: typeof BrandsBrandIdContainersRoute
    }
    '/brands/$brandId/containers/$containerId': {
      id: '/brands/$brandId/containers/$containerId'
      path: '/$containerId'
      fullPath: '/brands/$brandId/containers/$containerId'
      preLoaderRoute: typeof BrandsBrandIdContainersContainerIdRouteImport
      parentRoute: typeof BrandsBrandIdContainersRoute
    }
    '/api/brands/$brandId/packages': {
      id: '/api/brands/$brandId/packages'
      path: '/packages'
      fullPath: '/api/brands/$brandId/packages'
      preLoaderRoute: typeof ApiBrandsBrandIdPackagesRouteImport
      parentRoute: typeof ApiBrandsBrandIdRoute
    }
    '/api/brands/$brandId/materials': {
      id: '/api/brands/$brandId/materials'
      path: '/materials'
      fullPath: '/api/brands/$brandId/materials'
      preLoaderRoute: typeof ApiBrandsBrandIdMaterialsRouteImport
      parentRoute: typeof ApiBrandsBrandIdRoute
    }
    '/api/brands/$brandId/counts': {
      id: '/api/brands/$brandId/counts'
      path: '/counts'
      fullPath: '/api/brands/$brandId/counts'
      preLoaderRoute: typeof ApiBrandsBrandIdCountsRouteImport
      parentRoute: typeof ApiBrandsBrandIdRoute
    }
    '/brands/$brandId/packages/$packageId/': {
      id: '/brands/$brandId/packages/$packageId/'
      path: '/'
      fullPath: '/brands/$brandId/packages/$packageId/'
      preLoaderRoute: typeof BrandsBrandIdPackagesPackageIdIndexRouteImport
      parentRoute: typeof BrandsBrandIdPackagesPackageIdRoute
    }
    '/brands/$brandId/materials/$materialId/': {
      id: '/brands/$brandId/materials/$materialId/'
      path: '/'
      fullPath: '/brands/$brandId/materials/$materialId/'
      preLoaderRoute: typeof BrandsBrandIdMaterialsMaterialIdIndexRouteImport
      parentRoute: typeof BrandsBrandIdMaterialsMaterialIdRoute
    }
    '/brands/$brandId/containers/$containerId/': {
      id: '/brands/$brandId/containers/$containerId/'
      path: '/'
      fullPath: '/brands/$brandId/containers/$containerId/'
      preLoaderRoute: typeof BrandsBrandIdContainersContainerIdIndexRouteImport
      parentRoute: typeof BrandsBrandIdContainersContainerIdRoute
    }
    '/brands/$brandId/packages/$packageId/edit': {
      id: '/brands/$brandId/packages/$packageId/edit'
      path: '/edit'
      fullPath: '/brands/$brandId/packages/$packageId/edit'
      preLoaderRoute: typeof BrandsBrandIdPackagesPackageIdEditRouteImport
      parentRoute: typeof BrandsBrandIdPackagesPackageIdRoute
    }
    '/brands/$brandId/materials/$materialId/edit': {
      id: '/brands/$brandId/materials/$materialId/edit'
      path: '/edit'
      fullPath: '/brands/$brandId/materials/$materialId/edit'
      preLoaderRoute: typeof BrandsBrandIdMaterialsMaterialIdEditRouteImport
      parentRoute: typeof BrandsBrandIdMaterialsMaterialIdRoute
    }
    '/brands/$brandId/containers/$containerId/edit': {
      id: '/brands/$brandId/containers/$containerId/edit'
      path: '/edit'
      fullPath: '/brands/$brandId/containers/$containerId/edit'
      preLoaderRoute: typeof BrandsBrandIdContainersContainerIdEditRouteImport
      parentRoute: typeof BrandsBrandIdContainersContainerIdRoute
    }
    '/api/brands/$brandId/packages/new': {
      id: '/api/brands/$brandId/packages/new'
      path: '/new'
      fullPath: '/api/brands/$brandId/packages/new'
      preLoaderRoute: typeof ApiBrandsBrandIdPackagesNewRouteImport
      parentRoute: typeof ApiBrandsBrandIdPackagesRoute
    }
    '/api/brands/$brandId/packages/$packageId': {
      id: '/api/brands/$brandId/packages/$packageId'
      path: '/$packageId'
      fullPath: '/api/brands/$brandId/packages/$packageId'
      preLoaderRoute: typeof ApiBrandsBrandIdPackagesPackageIdRouteImport
      parentRoute: typeof ApiBrandsBrandIdPackagesRoute
    }
    '/api/brands/$brandId/materials/new': {
      id: '/api/brands/$brandId/materials/new'
      path: '/new'
      fullPath: '/api/brands/$brandId/materials/new'
      preLoaderRoute: typeof ApiBrandsBrandIdMaterialsNewRouteImport
      parentRoute: typeof ApiBrandsBrandIdMaterialsRoute
    }
    '/api/brands/$brandId/materials/$materialId': {
      id: '/api/brands/$brandId/materials/$materialId'
      path: '/$materialId'
      fullPath: '/api/brands/$brandId/materials/$materialId'
      preLoaderRoute: typeof ApiBrandsBrandIdMaterialsMaterialIdRouteImport
      parentRoute: typeof ApiBrandsBrandIdMaterialsRoute
    }
    '/api/assets/$brandSlug/$materialSlug/$filename': {
      id: '/api/assets/$brandSlug/$materialSlug/$filename'
      path: '/api/assets/$brandSlug/$materialSlug/$filename'
      fullPath: '/api/assets/$brandSlug/$materialSlug/$filename'
      preLoaderRoute: typeof ApiAssetsBrandSlugMaterialSlugFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BrandsBrandIdContainersContainerIdRouteChildren {
  BrandsBrandIdContainersContainerIdEditRoute: typeof BrandsBrandIdContainersContainerIdEditRoute
  BrandsBrandIdContainersContainerIdIndexRoute: typeof BrandsBrandIdContainersContainerIdIndexRoute
}

const BrandsBrandIdContainersContainerIdRouteChildren: BrandsBrandIdContainersContainerIdRouteChildren =
  {
    BrandsBrandIdContainersContainerIdEditRoute:
      BrandsBrandIdContainersContainerIdEditRoute,
    BrandsBrandIdContainersContainerIdIndexRoute:
      BrandsBrandIdContainersContainerIdIndexRoute,
  }

const BrandsBrandIdContainersContainerIdRouteWithChildren =
  BrandsBrandIdContainersContainerIdRoute._addFileChildren(
    BrandsBrandIdContainersContainerIdRouteChildren,
  )

interface BrandsBrandIdContainersRouteChildren {
  BrandsBrandIdContainersContainerIdRoute: typeof BrandsBrandIdContainersContainerIdRouteWithChildren
  BrandsBrandIdContainersCreateRoute: typeof BrandsBrandIdContainersCreateRoute
}

const BrandsBrandIdContainersRouteChildren: BrandsBrandIdContainersRouteChildren =
  {
    BrandsBrandIdContainersContainerIdRoute:
      BrandsBrandIdContainersContainerIdRouteWithChildren,
    BrandsBrandIdContainersCreateRoute: BrandsBrandIdContainersCreateRoute,
  }

const BrandsBrandIdContainersRouteWithChildren =
  BrandsBrandIdContainersRoute._addFileChildren(
    BrandsBrandIdContainersRouteChildren,
  )

interface BrandsBrandIdMaterialsMaterialIdRouteChildren {
  BrandsBrandIdMaterialsMaterialIdEditRoute: typeof BrandsBrandIdMaterialsMaterialIdEditRoute
  BrandsBrandIdMaterialsMaterialIdIndexRoute: typeof BrandsBrandIdMaterialsMaterialIdIndexRoute
}

const BrandsBrandIdMaterialsMaterialIdRouteChildren: BrandsBrandIdMaterialsMaterialIdRouteChildren =
  {
    BrandsBrandIdMaterialsMaterialIdEditRoute:
      BrandsBrandIdMaterialsMaterialIdEditRoute,
    BrandsBrandIdMaterialsMaterialIdIndexRoute:
      BrandsBrandIdMaterialsMaterialIdIndexRoute,
  }

const BrandsBrandIdMaterialsMaterialIdRouteWithChildren =
  BrandsBrandIdMaterialsMaterialIdRoute._addFileChildren(
    BrandsBrandIdMaterialsMaterialIdRouteChildren,
  )

interface BrandsBrandIdMaterialsRouteChildren {
  BrandsBrandIdMaterialsMaterialIdRoute: typeof BrandsBrandIdMaterialsMaterialIdRouteWithChildren
  BrandsBrandIdMaterialsCreateRoute: typeof BrandsBrandIdMaterialsCreateRoute
}

const BrandsBrandIdMaterialsRouteChildren: BrandsBrandIdMaterialsRouteChildren =
  {
    BrandsBrandIdMaterialsMaterialIdRoute:
      BrandsBrandIdMaterialsMaterialIdRouteWithChildren,
    BrandsBrandIdMaterialsCreateRoute: BrandsBrandIdMaterialsCreateRoute,
  }

const BrandsBrandIdMaterialsRouteWithChildren =
  BrandsBrandIdMaterialsRoute._addFileChildren(
    BrandsBrandIdMaterialsRouteChildren,
  )

interface BrandsBrandIdPackagesPackageIdRouteChildren {
  BrandsBrandIdPackagesPackageIdEditRoute: typeof BrandsBrandIdPackagesPackageIdEditRoute
  BrandsBrandIdPackagesPackageIdIndexRoute: typeof BrandsBrandIdPackagesPackageIdIndexRoute
}

const BrandsBrandIdPackagesPackageIdRouteChildren: BrandsBrandIdPackagesPackageIdRouteChildren =
  {
    BrandsBrandIdPackagesPackageIdEditRoute:
      BrandsBrandIdPackagesPackageIdEditRoute,
    BrandsBrandIdPackagesPackageIdIndexRoute:
      BrandsBrandIdPackagesPackageIdIndexRoute,
  }

const BrandsBrandIdPackagesPackageIdRouteWithChildren =
  BrandsBrandIdPackagesPackageIdRoute._addFileChildren(
    BrandsBrandIdPackagesPackageIdRouteChildren,
  )

interface BrandsBrandIdPackagesRouteChildren {
  BrandsBrandIdPackagesPackageIdRoute: typeof BrandsBrandIdPackagesPackageIdRouteWithChildren
  BrandsBrandIdPackagesCreateRoute: typeof BrandsBrandIdPackagesCreateRoute
}

const BrandsBrandIdPackagesRouteChildren: BrandsBrandIdPackagesRouteChildren = {
  BrandsBrandIdPackagesPackageIdRoute:
    BrandsBrandIdPackagesPackageIdRouteWithChildren,
  BrandsBrandIdPackagesCreateRoute: BrandsBrandIdPackagesCreateRoute,
}

const BrandsBrandIdPackagesRouteWithChildren =
  BrandsBrandIdPackagesRoute._addFileChildren(
    BrandsBrandIdPackagesRouteChildren,
  )

interface BrandsBrandIdRouteChildren {
  BrandsBrandIdContainersRoute: typeof BrandsBrandIdContainersRouteWithChildren
  BrandsBrandIdMaterialsRoute: typeof BrandsBrandIdMaterialsRouteWithChildren
  BrandsBrandIdPackagesRoute: typeof BrandsBrandIdPackagesRouteWithChildren
  BrandsBrandIdIndexRoute: typeof BrandsBrandIdIndexRoute
}

const BrandsBrandIdRouteChildren: BrandsBrandIdRouteChildren = {
  BrandsBrandIdContainersRoute: BrandsBrandIdContainersRouteWithChildren,
  BrandsBrandIdMaterialsRoute: BrandsBrandIdMaterialsRouteWithChildren,
  BrandsBrandIdPackagesRoute: BrandsBrandIdPackagesRouteWithChildren,
  BrandsBrandIdIndexRoute: BrandsBrandIdIndexRoute,
}

const BrandsBrandIdRouteWithChildren = BrandsBrandIdRoute._addFileChildren(
  BrandsBrandIdRouteChildren,
)

interface BrandsRouteChildren {
  BrandsBrandIdRoute: typeof BrandsBrandIdRouteWithChildren
  BrandsIndexRoute: typeof BrandsIndexRoute
}

const BrandsRouteChildren: BrandsRouteChildren = {
  BrandsBrandIdRoute: BrandsBrandIdRouteWithChildren,
  BrandsIndexRoute: BrandsIndexRoute,
}

const BrandsRouteWithChildren =
  BrandsRoute._addFileChildren(BrandsRouteChildren)

interface ContainersContainerIdRouteChildren {
  ContainersContainerIdEditRoute: typeof ContainersContainerIdEditRoute
  ContainersContainerIdIndexRoute: typeof ContainersContainerIdIndexRoute
}

const ContainersContainerIdRouteChildren: ContainersContainerIdRouteChildren = {
  ContainersContainerIdEditRoute: ContainersContainerIdEditRoute,
  ContainersContainerIdIndexRoute: ContainersContainerIdIndexRoute,
}

const ContainersContainerIdRouteWithChildren =
  ContainersContainerIdRoute._addFileChildren(
    ContainersContainerIdRouteChildren,
  )

interface ContainersRouteChildren {
  ContainersContainerIdRoute: typeof ContainersContainerIdRouteWithChildren
  ContainersCreateRoute: typeof ContainersCreateRoute
  ContainersIndexRoute: typeof ContainersIndexRoute
}

const ContainersRouteChildren: ContainersRouteChildren = {
  ContainersContainerIdRoute: ContainersContainerIdRouteWithChildren,
  ContainersCreateRoute: ContainersCreateRoute,
  ContainersIndexRoute: ContainersIndexRoute,
}

const ContainersRouteWithChildren = ContainersRoute._addFileChildren(
  ContainersRouteChildren,
)

interface EnumRouteChildren {
  EnumTableRoute: typeof EnumTableRoute
  EnumIndexRoute: typeof EnumIndexRoute
}

const EnumRouteChildren: EnumRouteChildren = {
  EnumTableRoute: EnumTableRoute,
  EnumIndexRoute: EnumIndexRoute,
}

const EnumRouteWithChildren = EnumRoute._addFileChildren(EnumRouteChildren)

interface ApiBrandsBrandIdMaterialsRouteChildren {
  ApiBrandsBrandIdMaterialsMaterialIdRoute: typeof ApiBrandsBrandIdMaterialsMaterialIdRoute
  ApiBrandsBrandIdMaterialsNewRoute: typeof ApiBrandsBrandIdMaterialsNewRoute
}

const ApiBrandsBrandIdMaterialsRouteChildren: ApiBrandsBrandIdMaterialsRouteChildren =
  {
    ApiBrandsBrandIdMaterialsMaterialIdRoute:
      ApiBrandsBrandIdMaterialsMaterialIdRoute,
    ApiBrandsBrandIdMaterialsNewRoute: ApiBrandsBrandIdMaterialsNewRoute,
  }

const ApiBrandsBrandIdMaterialsRouteWithChildren =
  ApiBrandsBrandIdMaterialsRoute._addFileChildren(
    ApiBrandsBrandIdMaterialsRouteChildren,
  )

interface ApiBrandsBrandIdPackagesRouteChildren {
  ApiBrandsBrandIdPackagesPackageIdRoute: typeof ApiBrandsBrandIdPackagesPackageIdRoute
  ApiBrandsBrandIdPackagesNewRoute: typeof ApiBrandsBrandIdPackagesNewRoute
}

const ApiBrandsBrandIdPackagesRouteChildren: ApiBrandsBrandIdPackagesRouteChildren =
  {
    ApiBrandsBrandIdPackagesPackageIdRoute:
      ApiBrandsBrandIdPackagesPackageIdRoute,
    ApiBrandsBrandIdPackagesNewRoute: ApiBrandsBrandIdPackagesNewRoute,
  }

const ApiBrandsBrandIdPackagesRouteWithChildren =
  ApiBrandsBrandIdPackagesRoute._addFileChildren(
    ApiBrandsBrandIdPackagesRouteChildren,
  )

interface ApiBrandsBrandIdRouteChildren {
  ApiBrandsBrandIdCountsRoute: typeof ApiBrandsBrandIdCountsRoute
  ApiBrandsBrandIdMaterialsRoute: typeof ApiBrandsBrandIdMaterialsRouteWithChildren
  ApiBrandsBrandIdPackagesRoute: typeof ApiBrandsBrandIdPackagesRouteWithChildren
}

const ApiBrandsBrandIdRouteChildren: ApiBrandsBrandIdRouteChildren = {
  ApiBrandsBrandIdCountsRoute: ApiBrandsBrandIdCountsRoute,
  ApiBrandsBrandIdMaterialsRoute: ApiBrandsBrandIdMaterialsRouteWithChildren,
  ApiBrandsBrandIdPackagesRoute: ApiBrandsBrandIdPackagesRouteWithChildren,
}

const ApiBrandsBrandIdRouteWithChildren =
  ApiBrandsBrandIdRoute._addFileChildren(ApiBrandsBrandIdRouteChildren)

interface ApiBrandsRouteChildren {
  ApiBrandsBrandIdRoute: typeof ApiBrandsBrandIdRouteWithChildren
  ApiBrandsBasicRoute: typeof ApiBrandsBasicRoute
}

const ApiBrandsRouteChildren: ApiBrandsRouteChildren = {
  ApiBrandsBrandIdRoute: ApiBrandsBrandIdRouteWithChildren,
  ApiBrandsBasicRoute: ApiBrandsBasicRoute,
}

const ApiBrandsRouteWithChildren = ApiBrandsRoute._addFileChildren(
  ApiBrandsRouteChildren,
)

interface ApiContainersRouteChildren {
  ApiContainersContainerIdRoute: typeof ApiContainersContainerIdRoute
  ApiContainersNewRoute: typeof ApiContainersNewRoute
}

const ApiContainersRouteChildren: ApiContainersRouteChildren = {
  ApiContainersContainerIdRoute: ApiContainersContainerIdRoute,
  ApiContainersNewRoute: ApiContainersNewRoute,
}

const ApiContainersRouteWithChildren = ApiContainersRoute._addFileChildren(
  ApiContainersRouteChildren,
)

interface ApiEnumRouteChildren {
  ApiEnumTableRoute: typeof ApiEnumTableRoute
}

const ApiEnumRouteChildren: ApiEnumRouteChildren = {
  ApiEnumTableRoute: ApiEnumTableRoute,
}

const ApiEnumRouteWithChildren =
  ApiEnumRoute._addFileChildren(ApiEnumRouteChildren)

interface ApiMaterialsRouteChildren {
  ApiMaterialsMaterialIdRoute: typeof ApiMaterialsMaterialIdRoute
}

const ApiMaterialsRouteChildren: ApiMaterialsRouteChildren = {
  ApiMaterialsMaterialIdRoute: ApiMaterialsMaterialIdRoute,
}

const ApiMaterialsRouteWithChildren = ApiMaterialsRoute._addFileChildren(
  ApiMaterialsRouteChildren,
)

interface ApiSchemaRouteChildren {
  ApiSchemaEntityRoute: typeof ApiSchemaEntityRoute
}

const ApiSchemaRouteChildren: ApiSchemaRouteChildren = {
  ApiSchemaEntityRoute: ApiSchemaEntityRoute,
}

const ApiSchemaRouteWithChildren = ApiSchemaRoute._addFileChildren(
  ApiSchemaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRoute: BrandsRouteWithChildren,
  ContainersRoute: ContainersRouteWithChildren,
  EnumRoute: EnumRouteWithChildren,
  ApiBrandsRoute: ApiBrandsRouteWithChildren,
  ApiContainersRoute: ApiContainersRouteWithChildren,
  ApiEnumRoute: ApiEnumRouteWithChildren,
  ApiMaterialsRoute: ApiMaterialsRouteWithChildren,
  ApiPackagesRoute: ApiPackagesRoute,
  ApiSchemaRoute: ApiSchemaRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAssetsBrandSlugMaterialSlugFilenameRoute:
    ApiAssetsBrandSlugMaterialSlugFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
